---

- name: checking to administration of resolv.conf by NetworkManager disabled
  command: grep -q '^dns=none' /etc/NetworkManager/NetworkManager.conf
  register: nmdns
  always_run: yes
  failed_when: no
  changed_when: nmdns.rc != 0

- name: be sure administration of resolv.conf by NetworkManager disabled
  lineinfile: >
    dest=/etc/NetworkManager/NetworkManager.conf
    insertafter='\[main\]'
    line='dns=none'
  when: nmdns|changed
  notify:
    - RESTART_NETWORK_MANAGER

- name: be sure our resolv.conf existed
  template: >
    src=resolv.conf.j2
    dest=/etc/resolv.conf
    mode=644
    owner=root
    group=root

...
